### ISSUE TITLE
Can we report hashes for no-cors same origin subresources?

### ISSUE THREAD

**Issue by yoavweiss** [yoavweiss/subresource-reporting#2]
I'm wondering if we could expand the CORS check to also cover same-origin subresources regardless of their CORS mode.
I'd love thoughts on that front.

^^ @ddworken @arturjanc @estark37 @camillelamy

**Comment by ddworken** [comment]
I don't see why not. The web platform generally doesn't try to enforce any trust boundaries on same-origin interactions, so allowing this seems quite reasonable. Especially since running `await (await fetch('https://example.com/', {mode: 'no-cors'})).text()` from `https://example.com` already allows accessing response bodies for a no-cors request.

**Comment by yoavweiss** [comment]
Thanks! (and TIL about `{mode: 'no-cors'}`. For some reason I thought that's not possible)

**Comment by yoavweiss** [comment]
Fixed with https://github.com/yoavweiss/subresource-reporting/commit/cfa52b9e607323b7ecd1de18dbac3ccc8ebe1c52

**Comment by yoavweiss** [comment]
I'm assuming that in case of a redirect chain that goes through a cross-origin request, we don't want to expose the hash. Is that a correct assumption?

**Comment by yoavweiss** [comment]
NM, as long as the response is not opaque, I'm assuming we can report the hashes. Cross-origin redirects render the response opaque.
